### ISSUE TITLE
"Projects" and "More" tabs not accessible by keyboard

### ISSUE THREAD

**Issue by TimJentzsch** [MurdoMaclachlan/website#25]
The "Projects" and "More" drop-down tabs cannot be focused with a keyboard and are therefore inaccessible to users that cannot use a mouse.

To reproduce, press "tab" several times on the page. You can see that the logo, the name and "Home" can be focused, but then it jumps to the main content of the page.

Expected: These drop-down tabs should be focusable, which should show the options of that drop-down which can then be focused one by one. Alternatively, you could focus the drop-down tab and it expands/collapses when pressing enter.

**Comment by MurdoMaclachlan** [comment]
Fixed in dev, merging to master soon.

**Comment by TimJentzsch** [comment]
As a general tip, an `a` element should always have a `href` attribute. Otherwise it's often better to use something like `button` if you want a click effect.
