### ISSUE TITLE
Email button on contact page should be link

### ISSUE THREAD

**Issue by TimJentzsch** [MurdoMaclachlan/website#27]
The email button on <https://murdomaclachlan.github.io/website/pages/contact.html> should be represented as an `a` tag instead of a `button`. The `href` attribute can be set to the `mailto` link.

This has the advantage that you don't need to manually set the click handler and it's more transparent what the button does to screen readers.
It also has the advantage that users can see on hover where the link leads to before clicking it.

**Comment by MurdoMaclachlan** [comment]
Fixed in dev, merging to master soon
