### ISSUE TITLE
Reduce number of nav links that lead to the home page

### ISSUE THREAD

**Issue by TimJentzsch** [MurdoMaclachlan/website#37]
Currently there are three links in the nav bar that get you back to the home page:

- Clicking on the eye logo
- Clicking on your name
- Clicking on "Home"

This can be slightly confusing for the sighted user, but is also three keypresses for the keyboard user.

I'd recommend to make it one link only, e.g. by doing the following:

- Remove the "Home" link
- Wrap the eye and your name in the same `a` tag to only have one link that does both

Of course there are other ways to change this, up to you :)

**Comment by MurdoMaclachlan** [comment]
I think I'll do this by making the eye and name not link anywhere and instead having "Home" be the first clickable/focusable thing there.

Having "Home" written out is a much stronger affordance for anyone who might be less familiar with common web design practices and therefore not know clicking the logo takes you to the home page.
